/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.salesdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.export.ExportOptions;

import com.salesdb.models.query.*;

public interface SalesdbQueryExecutorService {

    Page<AllSalesByRepResponse> executeAllSalesByRep(String channel, String id, Pageable pageable);

    void exportAllSalesByRep(String channel, String id, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<TotalLeadsResponse> executeTotalLeads(Pageable pageable);

    void exportTotalLeads(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<SalesByRepsResponse> executeSalesByReps(Integer channel, Pageable pageable);

    void exportSalesByReps(Integer channel, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<TopTrendingProductsResponse> executeTopTrendingProducts(Pageable pageable);

    void exportTopTrendingProducts(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<TotalSalesAndRevenueResponse> executeTotalSalesAndRevenue(Pageable pageable);

    void exportTotalSalesAndRevenue(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<SalesbyRepIdResponse> executeSalesbyRepId(String channel, Integer id, Pageable pageable);

    void exportSalesbyRepId(String channel, Integer id, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

}