/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.salesdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.sql.Date;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class AllSalesByRepResponse implements Serializable {


    @ColumnAlias("ID")
    private BigInteger id;

    @ColumnAlias("NAME")
    private String name;

    @ColumnAlias("SALEDATE")
    private Date saledate;

    @ColumnAlias("CUSTOMER")
    private String customer;

    @ColumnAlias("PRODUCT")
    private String product;

    @ColumnAlias("SALE")
    private BigInteger sale;

    public BigInteger getId() {
        return this.id;
    }

    public void setId(BigInteger id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Date getSaledate() {
        return this.saledate;
    }

    public void setSaledate(Date saledate) {
        this.saledate = saledate;
    }

    public String getCustomer() {
        return this.customer;
    }

    public void setCustomer(String customer) {
        this.customer = customer;
    }

    public String getProduct() {
        return this.product;
    }

    public void setProduct(String product) {
        this.product = product;
    }

    public BigInteger getSale() {
        return this.sale;
    }

    public void setSale(BigInteger sale) {
        this.sale = sale;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof AllSalesByRepResponse)) return false;
        final AllSalesByRepResponse allSalesByRepResponse = (AllSalesByRepResponse) o;
        return Objects.equals(getId(), allSalesByRepResponse.getId()) &&
                Objects.equals(getName(), allSalesByRepResponse.getName()) &&
                Objects.equals(getSaledate(), allSalesByRepResponse.getSaledate()) &&
                Objects.equals(getCustomer(), allSalesByRepResponse.getCustomer()) &&
                Objects.equals(getProduct(), allSalesByRepResponse.getProduct()) &&
                Objects.equals(getSale(), allSalesByRepResponse.getSale());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getName(),
                getSaledate(),
                getCustomer(),
                getProduct(),
                getSale());
    }
}