/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.salesdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class SalesbyRepIdResponse implements Serializable {


    @ColumnAlias("ID")
    private BigInteger id;

    @ColumnAlias("NAME")
    private String name;

    @ColumnAlias("LEADS")
    private BigInteger leads;

    @ColumnAlias("SALES")
    private BigInteger sales;

    public BigInteger getId() {
        return this.id;
    }

    public void setId(BigInteger id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public BigInteger getLeads() {
        return this.leads;
    }

    public void setLeads(BigInteger leads) {
        this.leads = leads;
    }

    public BigInteger getSales() {
        return this.sales;
    }

    public void setSales(BigInteger sales) {
        this.sales = sales;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SalesbyRepIdResponse)) return false;
        final SalesbyRepIdResponse salesbyRepIdResponse = (SalesbyRepIdResponse) o;
        return Objects.equals(getId(), salesbyRepIdResponse.getId()) &&
                Objects.equals(getName(), salesbyRepIdResponse.getName()) &&
                Objects.equals(getLeads(), salesbyRepIdResponse.getLeads()) &&
                Objects.equals(getSales(), salesbyRepIdResponse.getSales());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getName(),
                getLeads(),
                getSales());
    }
}